server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #\u6CE8\u518C\u8FDBEureka\u670D\u52A1\u5668\u7684\u5FAE\u670D\u52A1\u540D
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-dreamer/springcloud-config.git #GitHub\u4E0A\u9762\u7684git\u4ED3\u5E93\u540D\u5B57
          ####\u641C\u7D22\u76EE\u5F55
          search-paths:
            - springcloud-config
      ####\u8BFB\u53D6\u5206\u652F
      label: main
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#\u670D\u52A1\u6CE8\u518C\u5230eureka\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

other:
  testconfig: trueorfalse

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'