###consul\u670D\u52A1\u7AEF\u53E3\u53F7
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}


