server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.87.233:80


#\u6D88\u8D39\u8005\u5C06\u8981\u53BB\u8BBF\u95EE\u7684\u5FAE\u670D\u52A1\u540D\u79F0(\u6CE8\u518C\u6210\u529F\u8FDBnacos\u7684\u5FAE\u670D\u52A1\u63D0\u4F9B\u8005)
service-url:
  nacos-user-service: http://nacos-payment-provider


