
server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #\u914D\u7F6ENacos\u5730\u5740

management:
  endpoints:
    web:
      exposure:
        include: '*'





